<?php
$config['active_on'] = '1';
$config['application'] = 'MyTopix';
$config['banned_emails'] = '';
$config['banned_ips'] = '';
$config['banned_names'] = '';
$config['closed'] = '0';
$config['closed_message'] = 'This discussion board is currently closed for maintenance. We apologize for any inconvenience this may cause you.';
$config['cookie_domain'] = '';
$config['cookie_path'] = '/';
$config['cookie_prefix'] = 'my_';
$config['date_long'] = 'F j, Y \\a\\t h:i A';
$config['date_short'] = 'F j, Y \\a\\t h:i A';
$config['duplicate_emails'] = '';
$config['email_incoming'] = 'admin@mysite.com';
$config['email_name'] = 'MyTopix Message';
$config['email_outgoing'] = 'admin@mysite.com';
$config['emoticon_cols'] = '13';
$config['emoticon_rows'] = '2';
$config['hot_limit'] = '10';
$config['installed'] = '1176444184';
$config['language'] = 'english';
$config['latest_member_id'] = '2';
$config['latest_member_name'] = 'Wilhelm Murdoch';
$config['mailer_on'] = '1';
$config['max_images'] = '8';
$config['max_inline'] = '4';
$config['max_post'] = '50';
$config['min_post'] = '3';
$config['max_smilies'] = '8';
$config['notes_on'] = '1';
$config['page_sep'] = ' · ';
$config['per_page'] = '15';
$config['posts'] = '0';
$config['regs_on'] = '1';
$config['search_on'] = '1';
$config['servertime'] = '';
$config['site_link'] = 'http://localhost/mytopix/upload/';
$config['site_path'] = 'F://www-data//mytopix//upload/';
$config['skin'] = '1';
$config['stats_on'] = '1';
$config['title'] = 'My Community';
$config['topics'] = '1';
$config['total_members'] = '1';
$config['version'] = 'v 1.3.0';
$config['word_active'] = '1';
$config['wrap_on'] = '1';
$config['wrap_count'] = '100';
$config['flash_on'] = '1';
$config['flash_max_width'] = '300';
$config['flash_max_height'] = '300';
$config['good_image_types'] = 'gif|jpg|jpeg|tiff|png';
$config['subscribe_expire'] = '5';
$config['emoticons_rows'] = '2';
$config['validate_users'] = '1';
$config['most_online_date'] = '1176444184';
$config['most_online_count'] = '1';
$config['news_forum'] = '2';
$config['cutoff'] = '20';
$config['number_format'] = ',';
$config['topic_readers'] = '1';
$config['jump_on'] = '1';
$config['forum_viewers'] = '1';
$config['show_moderators'] = '0';
$config['show_subs'] = '1';
$config['bots_on'] = '1';
$config['bots_agents'] = 'googlebot=Google.com
slurp@inktomi=Hot Bot
ask jeeves=Ask Jeeves
lycos=Lycos.com
whatuseek=What You Seek
ia_archiver=Archive.org
msnbot=MSN Bot
Yahoo!=Yahoo.com';
$config['avatar_on'] = '1';
$config['avatar_use_flash'] = '1';
$config['avatar_ext'] = 'gif|jpg|jpeg|swf|png';
$config['avatar_use_remote'] = '1';
$config['avatar_upload_max'] = '15';
$config['avatar_default_dims'] = '87x50';
$config['avatar_max_dims'] = '100x100';
$config['dynamic_img_on'] = '0';
$config['calendar_on'] = '1';
$config['avatar_use_upload'] = '1';
$config['avatar_use_gallery'] = '1';
$config['polls_on'] = '1';
$config['attach_on'] = '1';
$config['coppa_on'] = '0';
$config['coppa_group'] = '5';
$config['coppa_fax'] = '';
$config['coppa_mail'] = '';
$config['recursive_stats'] = '1';
$config['cap_protect'] = '1';
$config['patch_version'] = '1.3.0';
$config['attach_ext'] = 'cgi|pl|js|asp|php|html|htm|jsp|jar|txt|rar|zip|ppt';
$config['forum_title'] = 'My Community';
$config['patch_build'] = '1.3.0';
?>